title: City University of Seattle Cybersecurity Club
description: #>- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

email: info@example.com
address: 123 Main St, Anytown, USA
twitter: example
facebook: example
linkedin: example

# Build settings
markdown: kramdown
theme: just-the-docs
plugins:
  - jekyll-avatar
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-github-metadata
  - jekyll-mentions
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-sass-converter
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings

# Exclude from processing.
# The following items will not be processed, by default.
exclude:
  - Gemfile
  - Gemfile.lock

collections:
  ctfs_and_challenges:
    output: true
    permalink: /:collection/:path
