title: City University of Seattle Cybersecurity Club
email: thomasthaddeus@cityuniversity.edu
description: >- # this means to ignore newlines until "baseurl:"
  This repository is a template right now for a jekyll server
  I'm creating for my schools cybersecurity club
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cyber.cityu.club" # the base hostname & protocol for your site
twitter_username: thaddeusmaxima
github_username: thomasthaddeus

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-avatar
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-github-metadata
  - jekyll-mentions
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-sass-converter
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings

# Exclude from processing.
# The following items will not be processed, by default.
exclude:
  - Gemfile
  - Gemfile.lock

collections:
  ctfs_and_challenges:
    output: true
    permalink: /:collection/:path
