source 'https://rubygems.org'

gem 'unicode-display_width'
gem 'terminal-table'
gem 'safe_yaml'
gem 'rouge'
gem 'forwardable-extended'
gem 'pathutil'
gem 'mercenary'
gem 'liquid'
gem 'kramdown'
gem 'kramdown-parser-gfm'
gem 'rb-inotify'
gem 'rb-fsevent'
gem 'listen'
gem 'jekyll-watch'
gem 'google-protobuf'
gem 'sass-embedded'
gem 'eventmachine'
gem 'colorator'
gem 'jekyll', '~> 4.3', '>= 4.3.2'
gem 'just-the-docs'
gem 'jekyll-avatar'
gem 'jekyll-coffeescript'
gem 'execjs'
gem 'jekyll-default-layout'
gem 'jekyll-email-protect'
gem 'jekyll-feed'
gem 'jekyll-github-metadata'
gem 'jekyll-github-metadata'
gem 'jekyll-mentions'
gem 'jekyll-optional-front-matter'
gem 'jekyll-paginate'
gem 'jekyll-readme-index'
gem 'jekyll-redirect-from'
gem 'jekyll-relative-links'
gem 'jekyll-sass-converter'
gem 'jekyll-seo-tag'
gem 'jekyll-sitemap'
gem 'jekyll-titles-from-headings'
gem "nokogiri", ">= 2.9.6"
gem "webrick", "~> 1.8"
